apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 430721128257.dkr.ecr.us-west-2.amazonaws.com/mayank-repo/my-app:latest
          ports:
            - containerPort: 80